### PR TITLE
fix: avoid duplicating scanned classes

### LINKED ISSUE #673: org.eclipse.lyo.oslc4j.provider.jena.ordfm.ResourcePackages.TYPES_MAPPINGS : the map value list can contain the same class multiple times
in the class org.eclipse.lyo.oslc4j.provider.jena.ordfm.ResourcePackages
the "public static synchronized void mapPackage(Package pkg)" method:

The method only scans a given input package once.
The name of the scanned package is placed in the SCANNED_PACKAGES set.

but the following code searches for classes recursively:
`    ClassGraph classGraph = new ClassGraph().acceptPackages(pkg.getName());
            classGraph = classGraph.enableClassInfo().enableAnnotationInfo();
            try (ScanResult scanResult = classGraph.scan()) {
                ClassInfoList classInforList = scanResult.getClassesWithAnnotation(OslcResourceShape.class.getName());
                for (ClassInfo classInfo : classInforList) {`

but the following code searches classes recursively and dins can find the same class multiple times.

To reproduce the problem, here is an example code (attached: [BugJena.java.txt](https://github.com/user-attachments/files/18298487/BugJena.java.txt) )
and the trace produced (also attached: [bug.log](https://github.com/user-attachments/files/18298482/bug.log) )

In the traces on lines 3 and 39, we can see the detection and addition of the class org.eclipse.lyo.oslc.domains.cm.ChangeRequest

The solution to the problem is
* either to change the type of  TYPES_MAPPINGS from Map<String, List<Class<?>>> to Map<String, Set<Class<?>>>
* or to check before adding in the list the absence of the class

### PR DESCRIPTION
**Pull request by berezovskyi**
## Description

Switch to Set instead of List for keeping a map of all RDF type URI to POJOs to avoid dupe POJO entries in the map.

## Checklist

- [x] This PR adds an entry to the CHANGELOG. _See https://keepachangelog.com/en/1.0.0/ for instructions. Minor edits are exempt._
- [ ] This PR was tested on at least one Lyo OSLC server (e.g. manual workflow on [Lyo Sample](https://github.com/OSLC/lyo-samples/actions/workflows/maven-smoke-manual.yml) and [OSLC RefImpl](https://github.com/oslc-op/refimpl/actions/workflows/maven-acceptance-manual.yml)) or adds unit/integration tests.
- [x] This PR does NOT break the API

## Issues

Closes #673

### CODE REVIEW

File: core/oslc4j-core/src/main/java/org/eclipse/lyo/oslc4j/provider/jena/ordfm/ResourcePackages.java [hunk 1]
```diff
@@ -49,7 +49,7 @@ public class ResourcePackages {
     /**
      * The RDFs-Classes types mapping.
      */
-    static final Map<String, List<Class<?>>> TYPES_MAPPINGS = new HashMap<>();
+    static final Map<String, Set<Class<?>>> TYPES_MAPPINGS = new HashMap<>();
```
Comment (berezovskyi) [inline core/oslc4j-core/src/main/java/org/eclipse/lyo/oslc4j/provider/jena/ordfm/ResourcePackages.java:52]: @ben81 please note that the map is not `"org.eclipse.lyo.oslc4j.provider.jena.resources.child.ChildAnimal" -> [ChildAnimal.class]` but instead `"http://locahost:7001/vocabulary/AbstractTypesTest2"->[ChildAnimal.class]`. It can happen that you annotate multiple classes with the same `@OslcNamespace("http://locahost:7001/vocabulary/")`/`@OslcResourceShape(title = "AbstractTypesTest2")` annotation pair and a collection on the map value is designed to handle this.

**Comment by berezovskyi** [comment]
PASS:

- https://github.com/OSLC/lyo-samples/actions/runs/12611508337
- https://github.com/oslc-op/refimpl/actions/runs/12611508938

**Comment by ben81** [comment]
The fix is good for me.
Thank you
